/**
 * Generated by Eclipse Mita 0.1.0.
 * @date 2019-05-31 09:54:04
 */


#include <XdkSensorHandle.h>
#include <BCDS_Environmental.h>
#include <bma2x2.h>
#include <string.h>
#include <inttypes.h>
#include <stdio.h>
#include <BCDS_Basics.h>
#include <BCDS_Retcode.h>
#include <stdint.h>
#include <stdbool.h>
#include "SensorEnvironment.h"
#include "SensorAccelerometer.h"
#include "PlatformXDK110.h"
#include "xdk110Types.h"
#include "InputOutputSDCardSd.h"
#include "ConnectivityLEDLed.h"
#include "MitaExceptions.h"
#include "MitaGeneratedTypes.h"
#include "application.h"

#ifndef BCDS_MODULE_ID
#define BCDS_MODULE_ID 0xCAFE
#endif

bool inactive = 0;
// buffer for cycle
uint8_t data_cycle_9[2];
// var cycle: array<uint8_t>
array_uint8_t cycle = {
	.data = data_cycle_9,
	.length = 2
};
uint32_t cycleTime = 0;
uint8_t cycleNum = 0;
bool orangeBlink = 0;
bool orangeOn = false;
uint8_t orangeBlinksRequested = 0;
int32_t blinkCounter = 0;
int32_t accelerationX = 0;
int32_t accelerationY = 0;
int32_t accelerationZ = 0;
uint32_t pressure = 0;

Retcode_T initGlobalVariables_application() {
	Retcode_T exception = RETCODE_OK;
	
	if(exception != NO_EXCEPTION) return exception;
	
	if(exception != NO_EXCEPTION) return exception;
	
	if(exception != NO_EXCEPTION) return exception;
	
	if(exception != NO_EXCEPTION) return exception;
	
	if(exception != NO_EXCEPTION) return exception;
	
	if(exception != NO_EXCEPTION) return exception;
	
	if(exception != NO_EXCEPTION) return exception;
	
	if(exception != NO_EXCEPTION) return exception;
	
	if(exception != NO_EXCEPTION) return exception;
	
	if(exception != NO_EXCEPTION) return exception;
	
	if(exception != NO_EXCEPTION) return exception;
	
	if(exception != NO_EXCEPTION) return exception;
	
	return exception;
}

Retcode_T HandleEveryXDK110Startup1(void* userParameter1, uint32_t userParameter2)
{
	
	BCDS_UNUSED(userParameter1);
	BCDS_UNUSED(userParameter2);

	Retcode_T exception = NO_EXCEPTION;
	
	
	bool _newConnectivityLEDLed_Red_1 = true;
	exception = ConnectivityLEDLed_Red_Write(&_newConnectivityLEDLed_Red_1);
	if(exception != NO_EXCEPTION) return exception;
	// buffer for init
	uint8_t data_init_2[2] = {0, 0};
	// var init: array<uint8_t>
	array_uint8_t init = {
		.data = data_init_2,
		.length = 2
	};
	
	
	array_uint8_t _newInputOutputSDCardSd_CycleInit_2 = init;
	exception = InputOutputSDCardSd_CycleInit_Write(&_newInputOutputSDCardSd_CycleInit_2);
	if(exception != NO_EXCEPTION) return exception;
	char result857607059_buf[29] = {0};
	char *result857607059 = result857607059_buf;
	
	char mainHandleEveryXDK110Startup11Result857607059_3_buf[29] = {0};
	snprintf(mainHandleEveryXDK110Startup11Result857607059_3_buf, sizeof(mainHandleEveryXDK110Startup11Result857607059_3_buf), "Status: ,Powered on \n \n \n");
	memcpy(result857607059, mainHandleEveryXDK110Startup11Result857607059_3_buf, sizeof(mainHandleEveryXDK110Startup11Result857607059_3_buf));
	
	char* _newInputOutputSDCardSd_Writer_3 = result857607059;
	exception = InputOutputSDCardSd_Writer_Write(&_newInputOutputSDCardSd_Writer_3);
	if(exception != NO_EXCEPTION) return exception;
	inactive = true;


	return NO_EXCEPTION;
}

Retcode_T HandleEveryButton_onePressed1(void* userParameter1, uint32_t userParameter2)
{
	
	BCDS_UNUSED(userParameter1);
	BCDS_UNUSED(userParameter2);

	Retcode_T exception = NO_EXCEPTION;
	
	
	if(inactive)
	{
		// buffer for result1523195251
		uint8_t data_result1523195251_2[2];
		// var result1523195251: array<uint8_t>
		array_uint8_t result1523195251 = {
			.data = data_result1523195251_2,
			.length = 2
		};
		
		exception = InputOutputSDCardSd_CycleReader_Read(&result1523195251);
		if(exception != NO_EXCEPTION) return exception;
		
		// cycle = result1523195251
		memcpy(cycle.data, result1523195251.data, sizeof(uint8_t) * cycle.length);
		if((cycle.data[0] == 0) && (cycle.data[1] == 0))
		{
			cycleNum = 0;
		}
		else
		{
			cycleNum = (cycle.data[0] * 10) + cycle.data[1];
		}
		
		cycleNum += 1;
		cycle.data[1] = cycleNum - ((cycleNum / 10) * 10);
		cycle.data[0] = cycleNum / 10;
		array_uint8_t _newInputOutputSDCardSd_CycleWriter_2 = cycle;
		exception = InputOutputSDCardSd_CycleWriter_Write(&_newInputOutputSDCardSd_CycleWriter_2);
		if(exception != NO_EXCEPTION) return exception;
		char result1533273090_buf[33] = {0};
		char *result1533273090 = result1533273090_buf;
		
		char IfStatement1Result1533273090_3_buf[33] = {0};
		snprintf(IfStatement1Result1533273090_3_buf, sizeof(IfStatement1Result1533273090_3_buf), "Data acquisition cycle: , %" PRIu8 " \n", cycleNum);
		memcpy(result1533273090, IfStatement1Result1533273090_3_buf, sizeof(IfStatement1Result1533273090_3_buf));
		
		char* _newInputOutputSDCardSd_Writer_3 = result1533273090;
		exception = InputOutputSDCardSd_Writer_Write(&_newInputOutputSDCardSd_Writer_3);
		if(exception != NO_EXCEPTION) return exception;
		PowerStatus platformXDK110ModalityPreparation_1;
		exception = XDK110_powerStatus_read(&platformXDK110ModalityPreparation_1);
		if(exception != NO_EXCEPTION) return exception;
		
		PowerStatus ps;
		ps = platformXDK110ModalityPreparation_1;
		switch(ps.tag) {
			case PowerStatus_Battery_e: {
				float level = ps.data.Battery;
				
					char result1000184784_buf[43] = {0};
					char *result1000184784 = result1000184784_buf;
					
					char IsDeconstructionCase0Result1000184784_5_buf[43] = {0};
					snprintf(IsDeconstructionCase0Result1000184784_5_buf, sizeof(IsDeconstructionCase0Result1000184784_5_buf), "Battery level: ,Approx. %.6g%% \n", level);
					memcpy(result1000184784, IsDeconstructionCase0Result1000184784_5_buf, sizeof(IsDeconstructionCase0Result1000184784_5_buf));
					
					char* _newInputOutputSDCardSd_Writer_4 = result1000184784;
					exception = InputOutputSDCardSd_Writer_Write(&_newInputOutputSDCardSd_Writer_4);
					if(exception != NO_EXCEPTION) return exception;
				
				break;
			}
			case PowerStatus_Corded_e: {
				
					char result1016853830_buf[28] = {0};
					char *result1016853830 = result1016853830_buf;
					
					char IsTypeMatchCase0Result1016853830_7_buf[28] = {0};
					snprintf(IsTypeMatchCase0Result1016853830_7_buf, sizeof(IsTypeMatchCase0Result1016853830_7_buf), "Battery level: ,Charging \n");
					memcpy(result1016853830, IsTypeMatchCase0Result1016853830_7_buf, sizeof(IsTypeMatchCase0Result1016853830_7_buf));
					
					char* _newInputOutputSDCardSd_Writer_5 = result1016853830;
					exception = InputOutputSDCardSd_Writer_Write(&_newInputOutputSDCardSd_Writer_5);
					if(exception != NO_EXCEPTION) return exception;
				
				break;
			}
		}
		
		char result798780870_buf[108] = {0};
		char *result798780870 = result798780870_buf;
		
		char IfStatement1Result798780870_8_buf[108] = {0};
		snprintf(IfStatement1Result798780870_8_buf, sizeof(IfStatement1Result798780870_8_buf), "Acceleration: X [raw] , Acceleration: Y [raw] , Acceleration: Z [raw] , Pressure [raw] , Cycle time [ms] \n");
		memcpy(result798780870, IfStatement1Result798780870_8_buf, sizeof(IfStatement1Result798780870_8_buf));
		
		char* _newInputOutputSDCardSd_Writer_6 = result798780870;
		exception = InputOutputSDCardSd_Writer_Write(&_newInputOutputSDCardSd_Writer_6);
		if(exception != NO_EXCEPTION) return exception;
		bool _newConnectivityLEDLed_Red_7 = false;
		exception = ConnectivityLEDLed_Red_Write(&_newConnectivityLEDLed_Red_7);
		if(exception != NO_EXCEPTION) return exception;
		bool _newConnectivityLEDLed_Yellow_8 = true;
		exception = ConnectivityLEDLed_Yellow_Write(&_newConnectivityLEDLed_Yellow_8);
		if(exception != NO_EXCEPTION) return exception;
		inactive = false;
	}
	else
	{
		char result2013802750_buf[58] = {0};
		char *result2013802750 = result2013802750_buf;
		
		char IfStatement160Result2013802750_9_buf[58] = {0};
		snprintf(IfStatement160Result2013802750_9_buf, sizeof(IfStatement160Result2013802750_9_buf), "Status: ,Data acquisition stopped by the user \n \n \n \n");
		memcpy(result2013802750, IfStatement160Result2013802750_9_buf, sizeof(IfStatement160Result2013802750_9_buf));
		
		char* _newInputOutputSDCardSd_Writer_9 = result2013802750;
		exception = InputOutputSDCardSd_Writer_Write(&_newInputOutputSDCardSd_Writer_9);
		if(exception != NO_EXCEPTION) return exception;
		bool _newConnectivityLEDLed_Red_10 = true;
		exception = ConnectivityLEDLed_Red_Write(&_newConnectivityLEDLed_Red_10);
		if(exception != NO_EXCEPTION) return exception;
		bool _newConnectivityLEDLed_Yellow_11 = false;
		exception = ConnectivityLEDLed_Yellow_Write(&_newConnectivityLEDLed_Yellow_11);
		if(exception != NO_EXCEPTION) return exception;
		inactive = true;
		cycleTime = 0;
	}


	return NO_EXCEPTION;
}

Retcode_T HandleEveryButton_twoPressed1(void* userParameter1, uint32_t userParameter2)
{
	
	BCDS_UNUSED(userParameter1);
	BCDS_UNUSED(userParameter2);

	Retcode_T exception = NO_EXCEPTION;
	
	
	if(!inactive)
	{
		orangeBlinksRequested = cycleNum;
		orangeBlink = true;
	}


	return NO_EXCEPTION;
}

Retcode_T HandleEvery20Millisecond1(void* userParameter1, uint32_t userParameter2)
{
	
	BCDS_UNUSED(userParameter1);
	BCDS_UNUSED(userParameter2);

	Retcode_T exception = NO_EXCEPTION;
	
	
	if(!inactive)
	{
		cycleTime += 1;
		struct bma2x2_accel_data sensorAccelerometerModalityPreparation_1;
		exception = SensorAccelerometer_ReadXYZ(&sensorAccelerometerModalityPreparation_1);
		if(exception != NO_EXCEPTION) return exception;
		
		accelerationX = sensorAccelerometerModalityPreparation_1.x;
		accelerationY = sensorAccelerometerModalityPreparation_1.y;
		accelerationZ = sensorAccelerometerModalityPreparation_1.z;
		Environmental_Data_T sensorEnvironmentModalityPreparation_2;
		exception = Environmental_readData(xdkEnvironmental_BME280_Handle, &sensorEnvironmentModalityPreparation_2);
		if(exception != NO_EXCEPTION) return exception;
		
		pressure = sensorEnvironmentModalityPreparation_2.pressure;
		double realCycleTime = cycleTime * 100;
		char result1650690825_buf[73] = {0};
		char *result1650690825 = result1650690825_buf;
		
		char IfStatement2Result1650690825_3_buf[73] = {0};
		snprintf(IfStatement2Result1650690825_3_buf, sizeof(IfStatement2Result1650690825_3_buf), "%" PRId32 " , %" PRId32 " , %" PRId32 " , %" PRIu32 " , %.6g \n", accelerationX, accelerationY, accelerationZ, pressure, realCycleTime);
		memcpy(result1650690825, IfStatement2Result1650690825_3_buf, sizeof(IfStatement2Result1650690825_3_buf));
		
		char* _newInputOutputSDCardSd_Writer_1 = result1650690825;
		exception = InputOutputSDCardSd_Writer_Write(&_newInputOutputSDCardSd_Writer_1);
		if(exception != NO_EXCEPTION) return exception;
	}


	return NO_EXCEPTION;
}

Retcode_T HandleEvery250Millisecond1(void* userParameter1, uint32_t userParameter2)
{
	
	BCDS_UNUSED(userParameter1);
	BCDS_UNUSED(userParameter2);

	Retcode_T exception = NO_EXCEPTION;
	
	
	if(!inactive)
	{
		if(orangeBlink)
		{
			if(orangeBlinksRequested > blinkCounter)
			{
				if(!orangeOn)
				{
					bool _newConnectivityLEDLed_Orange_1 = true;
					exception = ConnectivityLEDLed_Orange_Write(&_newConnectivityLEDLed_Orange_1);
					if(exception != NO_EXCEPTION) return exception;
					orangeOn = true;
				}
				else
				{
					bool _newConnectivityLEDLed_Orange_2 = false;
					exception = ConnectivityLEDLed_Orange_Write(&_newConnectivityLEDLed_Orange_2);
					if(exception != NO_EXCEPTION) return exception;
					orangeOn = false;
					blinkCounter += 1;
				}
			}
			else
			{
				blinkCounter = 0;
				orangeBlink = false;
				orangeBlinksRequested = 0;
			}
		}
	}


	return NO_EXCEPTION;
}


