/**
 * Generated by Eclipse Mita 0.1.0.
 * @date 2019-05-24 10:10:06
 */


#include <XdkSensorHandle.h>
#include <BCDS_Environmental.h>
#include <bma2x2.h>
#include <string.h>
#include <inttypes.h>
#include <stdio.h>
#include <BCDS_Basics.h>
#include <BCDS_Retcode.h>
#include <stdint.h>
#include <stdbool.h>
#include "SensorEnvironment.h"
#include "SensorAccelerometer.h"
#include "PlatformXDK110.h"
#include "xdk110Types.h"
#include "InputOutputSDCardSd.h"
#include "ConnectivityLEDLed.h"
#include "MitaExceptions.h"
#include "MitaGeneratedTypes.h"
#include "application.h"
#include <stdlib.h>

#ifndef BCDS_MODULE_ID
#define BCDS_MODULE_ID 0xCAFE
#endif

bool inactive = true;
// buffer for cycle
uint8_t data_cycle_9[2];
// var cycle: array<uint8_t>
array_uint8_t cycle = {
	.data = data_cycle_9,
	.length = 2
};
uint32_t cycleTime = 0;
uint8_t cycleNum = 0;
bool orangeBlink = 0;
bool orangeOn = false;
uint8_t orangeBlinksRequested = 0;
int32_t blinkCounter = 0;
int32_t accelerationX = 0;
int32_t accelerationY = 0;
int32_t accelerationZ = 0;
uint32_t pressure = 0;

Retcode_T initGlobalVariables_application() {
	Retcode_T exception = RETCODE_OK;
	
	if(exception != NO_EXCEPTION) return exception;
	
	if(exception != NO_EXCEPTION) return exception;
	
	if(exception != NO_EXCEPTION) return exception;
	
	if(exception != NO_EXCEPTION) return exception;
	
	if(exception != NO_EXCEPTION) return exception;
	
	if(exception != NO_EXCEPTION) return exception;
	
	if(exception != NO_EXCEPTION) return exception;
	
	if(exception != NO_EXCEPTION) return exception;
	
	if(exception != NO_EXCEPTION) return exception;
	
	if(exception != NO_EXCEPTION) return exception;
	
	if(exception != NO_EXCEPTION) return exception;
	
	if(exception != NO_EXCEPTION) return exception;
	
	return exception;
}

Retcode_T HandleEveryXDK110Startup1(void* userParameter1, uint32_t userParameter2)
{
	
	BCDS_UNUSED(userParameter1);
	BCDS_UNUSED(userParameter2);

	Retcode_T exception = NO_EXCEPTION;
	
	
	bool _newConnectivityLEDLed_Red_1 = true;
	exception = ConnectivityLEDLed_Red_Write(&_newConnectivityLEDLed_Red_1);
	if(exception != NO_EXCEPTION) return exception;
	// buffer for init
	uint8_t data_init_2[2] = {0, 0};
	// var init: array<uint8_t>
	array_uint8_t init = {
		.data = data_init_2,
		.length = 2
	};
	
	
	array_uint8_t _newInputOutputSDCardSd_CycleInit_2 = init;
	exception = InputOutputSDCardSd_CycleInit_Write(&_newInputOutputSDCardSd_CycleInit_2);
	if(exception != NO_EXCEPTION) return exception;
	char result1207470102_buf[30] = {0};
	char *result1207470102 = result1207470102_buf;
	
	char mainHandleEveryXDK110Startup11Result1207470102_3_buf[30] = {0};
	snprintf(mainHandleEveryXDK110Startup11Result1207470102_3_buf, sizeof(mainHandleEveryXDK110Startup11Result1207470102_3_buf), "Status: , powered on \n \n \n");
	memcpy(result1207470102, mainHandleEveryXDK110Startup11Result1207470102_3_buf, sizeof(mainHandleEveryXDK110Startup11Result1207470102_3_buf));
	
	char* _newInputOutputSDCardSd_Writer_3 = result1207470102;
	exception = InputOutputSDCardSd_Writer_Write(&_newInputOutputSDCardSd_Writer_3);
	if(exception != NO_EXCEPTION) return exception;


	return NO_EXCEPTION;
}

Retcode_T HandleEveryButton_onePressed1(void* userParameter1, uint32_t userParameter2)
{
	
	BCDS_UNUSED(userParameter1);
	BCDS_UNUSED(userParameter2);

	Retcode_T exception = NO_EXCEPTION;
	
	
	if(inactive)
	{
		PowerStatus platformXDK110ModalityPreparation_1;
		exception = XDK110_powerStatus_read(&platformXDK110ModalityPreparation_1);
		if(exception != NO_EXCEPTION) return exception;
		
		PowerStatus ps;
		ps = platformXDK110ModalityPreparation_1;
		switch(ps.tag) {
			case PowerStatus_Battery_e: {
				float level = ps.data.Battery;
				
					char result286873007_buf[44] = {0};
					char *result286873007 = result286873007_buf;
					
					char IsDeconstructionCase0Result286873007_3_buf[44] = {0};
					snprintf(IsDeconstructionCase0Result286873007_3_buf, sizeof(IsDeconstructionCase0Result286873007_3_buf), "Battery level: , approx. %.6g%% \n", level);
					memcpy(result286873007, IsDeconstructionCase0Result286873007_3_buf, sizeof(IsDeconstructionCase0Result286873007_3_buf));
					
					char* _newInputOutputSDCardSd_Writer_1 = result286873007;
					exception = InputOutputSDCardSd_Writer_Write(&_newInputOutputSDCardSd_Writer_1);
					if(exception != NO_EXCEPTION) return exception;
				
				break;
			}
			case PowerStatus_Corded_e: {
				
					char result1988521857_buf[30] = {0};
					char *result1988521857 = result1988521857_buf;
					
					char IsTypeMatchCase0Result1988521857_5_buf[30] = {0};
					snprintf(IsTypeMatchCase0Result1988521857_5_buf, sizeof(IsTypeMatchCase0Result1988521857_5_buf), "Battery level: ,  charging \n");
					memcpy(result1988521857, IsTypeMatchCase0Result1988521857_5_buf, sizeof(IsTypeMatchCase0Result1988521857_5_buf));
					
					char* _newInputOutputSDCardSd_Writer_2 = result1988521857;
					exception = InputOutputSDCardSd_Writer_Write(&_newInputOutputSDCardSd_Writer_2);
					if(exception != NO_EXCEPTION) return exception;
				
				break;
			}
		}
		
		// buffer for result684573815
		uint8_t data_result684573815_6[2];
		// var result684573815: array<uint8_t>
		array_uint8_t result684573815 = {
			.data = data_result684573815_6,
			.length = 2
		};
		
		exception = InputOutputSDCardSd_CycleReader_Read(&result684573815);
		if(exception != NO_EXCEPTION) return exception;
		
		// cycle = result684573815
		memcpy(cycle.data, result684573815.data, sizeof(uint8_t) * cycle.length);
		if((cycle.data[0] == 0) && (cycle.data[1] == 0))
		{
			cycleNum = 0;
		}
		else
		{
			cycleNum = cycle.data[0] + (cycle.data[1] * 10);
		}
		
		cycleNum += 1;
		cycle.data[0] = cycleNum;
		cycle.data[1] = cycleNum / 10;
		array_uint8_t _newInputOutputSDCardSd_CycleWriter_4 = cycle;
		exception = InputOutputSDCardSd_CycleWriter_Write(&_newInputOutputSDCardSd_CycleWriter_4);
		if(exception != NO_EXCEPTION) return exception;
		char result1966993791_buf[33] = {0};
		char *result1966993791 = result1966993791_buf;
		
		char IfStatement1Result1966993791_7_buf[33] = {0};
		snprintf(IfStatement1Result1966993791_7_buf, sizeof(IfStatement1Result1966993791_7_buf), "Data acquisition cycle: , %" PRIu8 " \n", cycleNum);
		memcpy(result1966993791, IfStatement1Result1966993791_7_buf, sizeof(IfStatement1Result1966993791_7_buf));
		
		char* _newInputOutputSDCardSd_Writer_5 = result1966993791;
		exception = InputOutputSDCardSd_Writer_Write(&_newInputOutputSDCardSd_Writer_5);
		if(exception != NO_EXCEPTION) return exception;
		char result1997935594_buf[108] = {0};
		char *result1997935594 = result1997935594_buf;
		
		char IfStatement1Result1997935594_8_buf[108] = {0};
		snprintf(IfStatement1Result1997935594_8_buf, sizeof(IfStatement1Result1997935594_8_buf), "Acceleration: X [raw] , Acceleration: Y [raw] , Acceleration: Z [raw] , Pressure [raw] , Cycle time [ms] \n");
		memcpy(result1997935594, IfStatement1Result1997935594_8_buf, sizeof(IfStatement1Result1997935594_8_buf));
		
		char* _newInputOutputSDCardSd_Writer_6 = result1997935594;
		exception = InputOutputSDCardSd_Writer_Write(&_newInputOutputSDCardSd_Writer_6);
		if(exception != NO_EXCEPTION) return exception;
		bool _newConnectivityLEDLed_Red_7 = false;
		exception = ConnectivityLEDLed_Red_Write(&_newConnectivityLEDLed_Red_7);
		if(exception != NO_EXCEPTION) return exception;
		bool _newConnectivityLEDLed_Yellow_8 = true;
		exception = ConnectivityLEDLed_Yellow_Write(&_newConnectivityLEDLed_Yellow_8);
		if(exception != NO_EXCEPTION) return exception;
		inactive = false;
	}
	else
	{
		char result841584878_buf[59] = {0};
		char *result841584878 = result841584878_buf;
		
		char IfStatement150Result841584878_9_buf[59] = {0};
		snprintf(IfStatement150Result841584878_9_buf, sizeof(IfStatement150Result841584878_9_buf), "Status: , data acquisition stopped by the user \n \n \n \n");
		memcpy(result841584878, IfStatement150Result841584878_9_buf, sizeof(IfStatement150Result841584878_9_buf));
		
		char* _newInputOutputSDCardSd_Writer_9 = result841584878;
		exception = InputOutputSDCardSd_Writer_Write(&_newInputOutputSDCardSd_Writer_9);
		if(exception != NO_EXCEPTION) return exception;
		bool _newConnectivityLEDLed_Red_10 = true;
		exception = ConnectivityLEDLed_Red_Write(&_newConnectivityLEDLed_Red_10);
		if(exception != NO_EXCEPTION) return exception;
		bool _newConnectivityLEDLed_Yellow_11 = false;
		exception = ConnectivityLEDLed_Yellow_Write(&_newConnectivityLEDLed_Yellow_11);
		if(exception != NO_EXCEPTION) return exception;
		inactive = true;
		cycleTime = 0;
	}


	return NO_EXCEPTION;
}

Retcode_T HandleEveryButton_twoPressed1(void* userParameter1, uint32_t userParameter2)
{
	
	BCDS_UNUSED(userParameter1);
	BCDS_UNUSED(userParameter2);

	Retcode_T exception = NO_EXCEPTION;
	
	
	if(!inactive)
	{
		orangeBlinksRequested = cycleNum;
		orangeBlink = true;
	}


	return NO_EXCEPTION;
}

Retcode_T HandleEvery20Millisecond1(void* userParameter1, uint32_t userParameter2)
{
	
	BCDS_UNUSED(userParameter1);
	BCDS_UNUSED(userParameter2);

	Retcode_T exception = NO_EXCEPTION;
	
	
	if(!inactive)
	{
		cycleTime += 20;
		struct bma2x2_accel_data sensorAccelerometerModalityPreparation_1;
		exception = SensorAccelerometer_ReadXYZ(&sensorAccelerometerModalityPreparation_1);
		if(exception != NO_EXCEPTION) return exception;
		
		accelerationX = sensorAccelerometerModalityPreparation_1.x;
		accelerationY = sensorAccelerometerModalityPreparation_1.y;
		accelerationZ = sensorAccelerometerModalityPreparation_1.z;
		Environmental_Data_T sensorEnvironmentModalityPreparation_2;
		exception = Environmental_readData(xdkEnvironmental_BME280_Handle, &sensorEnvironmentModalityPreparation_2);
		if(exception != NO_EXCEPTION) return exception;
		
		pressure = sensorEnvironmentModalityPreparation_2.pressure;
		char result679815645_buf[69] = {0};
		char *result679815645 = result679815645_buf;
		
		char IfStatement2Result679815645_2_buf[69] = {0};
		snprintf(IfStatement2Result679815645_2_buf, sizeof(IfStatement2Result679815645_2_buf), "%" PRId32 " , %" PRId32 " , %" PRId32 " , %" PRIu32 " , %" PRIu32 " \n", accelerationX, accelerationY, accelerationZ, pressure, cycleTime);
		memcpy(result679815645, IfStatement2Result679815645_2_buf, sizeof(IfStatement2Result679815645_2_buf));
		
		char* _newInputOutputSDCardSd_Writer_1 = result679815645;
		exception = InputOutputSDCardSd_Writer_Write(&_newInputOutputSDCardSd_Writer_1);
		if(exception != NO_EXCEPTION) return exception;
	}


	return NO_EXCEPTION;
}

Retcode_T HandleEvery200Millisecond1(void* userParameter1, uint32_t userParameter2)
{
	
	BCDS_UNUSED(userParameter1);
	BCDS_UNUSED(userParameter2);

	Retcode_T exception = NO_EXCEPTION;
	
	
	if(!inactive)
	{
		if(orangeBlink)
		{
			if(orangeBlinksRequested > blinkCounter)
			{
				if(!orangeOn)
				{
					bool _newConnectivityLEDLed_Orange_1 = true;
					exception = ConnectivityLEDLed_Orange_Write(&_newConnectivityLEDLed_Orange_1);
					if(exception != NO_EXCEPTION) return exception;
					orangeOn = true;
				}
				else
				{
					bool _newConnectivityLEDLed_Orange_2 = false;
					exception = ConnectivityLEDLed_Orange_Write(&_newConnectivityLEDLed_Orange_2);
					if(exception != NO_EXCEPTION) return exception;
					orangeOn = false;
					blinkCounter += 1;
				}
			}
			else
			{
				blinkCounter = 0;
				orangeBlink = false;
				orangeBlinksRequested = 0;
			}
		}
	}


	return NO_EXCEPTION;
}


