/**
 * Generated by Eclipse Mita 0.1.0.
 * @date 2019-05-31 11:05:36
 */


#ifndef APPLICATION_H
#define APPLICATION_H

#include <BCDS_Retcode.h>
#include "applicationTypes.h"


Retcode_T initGlobalVariables_application();

#endif
