/**
 * Generated by Eclipse Mita 0.1.0.
 * @date 2019-05-23 10:33:59
 */


#ifndef CONNECTIVITYLED_LED_H
#define CONNECTIVITYLED_LED_H

#include <stdbool.h>
#include <BCDS_Retcode.h>


/**
 * Sets up the LED.
 */
Retcode_T ConnectivityLEDLed_Setup(void);

/**
 * Enables the LED sensor.
 */
Retcode_T ConnectivityLEDLed_Enable(void);

/**
 * Provides read access to red.
 */
Retcode_T ConnectivityLEDLed_Red_Read(bool* result);

/**
 * Provides write access to red.
 */
Retcode_T ConnectivityLEDLed_Red_Write(bool* result);
/**
 * Provides read access to orange.
 */
Retcode_T ConnectivityLEDLed_Orange_Read(bool* result);

/**
 * Provides write access to orange.
 */
Retcode_T ConnectivityLEDLed_Orange_Write(bool* result);
/**
 * Provides read access to yellow.
 */
Retcode_T ConnectivityLEDLed_Yellow_Read(bool* result);

/**
 * Provides write access to yellow.
 */
Retcode_T ConnectivityLEDLed_Yellow_Write(bool* result);


#endif
