/**
 * Generated by Eclipse Mita 0.1.0.
 * @date 2019-05-23 19:47:53
 */


#ifndef INPUTOUTPUTSDCARD_SDCARD_H
#define INPUTOUTPUTSDCARD_SDCARD_H

#include <BCDS_Retcode.h>


/**
 * Sets up the SDCard.
 */
Retcode_T InputOutputSDCardSd_Setup(void);

/**
 * Enables the SDCard sensor.
 */
Retcode_T InputOutputSDCardSd_Enable(void);

/**
 * Provides read access to writer.
 */
Retcode_T InputOutputSDCardSd_Writer_Read(char** result);

/**
 * Provides write access to writer.
 */
Retcode_T InputOutputSDCardSd_Writer_Write(char** result);
/**
 * Provides read access to cycleInit.
 */
Retcode_T InputOutputSDCardSd_CycleInit_Read(char** result);

/**
 * Provides write access to cycleInit.
 */
Retcode_T InputOutputSDCardSd_CycleInit_Write(char** result);
/**
 * Provides read access to cycleWriter.
 */
Retcode_T InputOutputSDCardSd_CycleWriter_Read(char** result);

/**
 * Provides write access to cycleWriter.
 */
Retcode_T InputOutputSDCardSd_CycleWriter_Write(char** result);
/**
 * Provides read access to cycleReader.
 */
Retcode_T InputOutputSDCardSd_CycleReader_Read(char** result);

/**
 * Provides write access to cycleReader.
 */
Retcode_T InputOutputSDCardSd_CycleReader_Write(char** result);


#endif
