/**
 * Generated by Eclipse Mita 0.1.0.
 * @date 2019-05-24 10:10:06
 */


#ifndef INPUTOUTPUTSDCARD_SDCARD_H
#define INPUTOUTPUTSDCARD_SDCARD_H

#include <stdint.h>
#include <BCDS_Retcode.h>
#include "MitaGeneratedTypes.h"


/**
 * Sets up the SDCard.
 */
Retcode_T InputOutputSDCardSd_Setup(void);

/**
 * Enables the SDCard sensor.
 */
Retcode_T InputOutputSDCardSd_Enable(void);

/**
 * Provides read access to writer.
 */
Retcode_T InputOutputSDCardSd_Writer_Read(char** result);

/**
 * Provides write access to writer.
 */
Retcode_T InputOutputSDCardSd_Writer_Write(char** result);
/**
 * Provides read access to cycleInit.
 */
Retcode_T InputOutputSDCardSd_CycleInit_Read(array_uint8_t* result);

/**
 * Provides write access to cycleInit.
 */
Retcode_T InputOutputSDCardSd_CycleInit_Write(array_uint8_t* result);
/**
 * Provides read access to cycleWriter.
 */
Retcode_T InputOutputSDCardSd_CycleWriter_Read(array_uint8_t* result);

/**
 * Provides write access to cycleWriter.
 */
Retcode_T InputOutputSDCardSd_CycleWriter_Write(array_uint8_t* result);
/**
 * Provides read access to cycleReader.
 */
Retcode_T InputOutputSDCardSd_CycleReader_Read(array_uint8_t* result);

/**
 * Provides write access to cycleReader.
 */
Retcode_T InputOutputSDCardSd_CycleReader_Write(array_uint8_t* result);


#endif
