/**
 * Generated by Eclipse Mita 0.1.0.
 * @date 2019-05-31 09:54:04
 */


#ifndef MITA_TIME_H
#define MITA_TIME_H

#include <BCDS_Retcode.h>


Retcode_T SetupTime(void);

Retcode_T EnableTime(void);

Retcode_T EveryHandleEvery20Millisecond1_Enable(void);
Retcode_T EveryHandleEvery250Millisecond1_Enable(void);


#endif
