/**
 * Generated by Eclipse Mita 0.1.0.
 * @date 2019-05-23 19:47:53
 */


#ifndef MITA_TIME_H
#define MITA_TIME_H

#include <BCDS_Retcode.h>


Retcode_T SetupTime(void);

Retcode_T EnableTime(void);

Retcode_T EveryHandleEvery10Millisecond1_Enable(void);
Retcode_T EveryHandleEvery200Millisecond1_Enable(void);


#endif
