/**
 * Generated by Eclipse Mita 0.1.0.
 * @date 2019-05-24 10:40:01
 */


#ifndef MITA_GENERATED_TYPES_H
#define MITA_GENERATED_TYPES_H

#include <stdint.h>
#include "MitaGeneratedTypes.h"
#include "applicationTypes.h"






typedef struct {
	uint8_t* data;
	uint32_t length;
} array_uint8_t;




#endif
