/**
 * Generated by Eclipse Mita 0.1.0.
 * @date 2019-05-23 10:33:59
 */


#ifndef SENSORBUTTON_TWO_BUTTON_TWO_H
#define SENSORBUTTON_TWO_BUTTON_TWO_H

#include <BCDS_Retcode.h>


/**
 * Sets up the button_two.
 */
Retcode_T SensorButton_two_Setup(void);

/**
 * Enables the button_two sensor.
 */
Retcode_T SensorButton_two_Enable(void);



#endif
